version: '3.8'

services:
  server:
    image: daily-dash
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    command: sh -c "npm run migrate && npm start"
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./views:/app/views
    env_file: ./secrets/.env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '$DB_USERNAME']
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: ./secrets/.env

  cache:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    env_file: ./secrets/.env

volumes:
  db-data:
  cache-data:
