services:
  server:
    image: daily-dash
    restart: always
    ports:
      - ${PORT}:443
      - ${DEBUG_PORT}:${DEBUG_PORT}
    volumes:
      - ./dist:/app/dist
      - ./nodemon.json:/app/nodemon.json
      - ./public:/app/public
      - ./views:/app/views
      - ./secrets:/app/secrets
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    env_file: ./secrets/.env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  db:
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: ./secrets/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '$DB_USERNAME']
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - cache-data:/data
    env_file: ./secrets/.env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  cache-data:
